module.exports = {
    "10McCOM": "10 MHz Geographic Overlap Review Completed",
    "10MOFF": "Offlined 10 MHz Geographic Overlap Review",
    "20COM": "2065/2079 Review Completed",
    "20OFF": "Offlined for 2065/2079 Review",
    "38GHCO": "38.6 - 40 GHz Review completed",
    "38GOFF": "Offlined For 38.6 - 40 GHz Review",
    "72OCOM": "72-76 MHz Coordination Completed (Op Fixed)",
    "72OOFF": "Offlined for 72-76 MHz Coordination (Op Fixed)",
    "72CCOM": "72-76 MHz Coordination Completed (Channel 4/5)",
    "72COFF": "Offlined for 72-76 MHz Coordination (Channel 4/5)",
    "800COM": "Completed 800 MHz Band Reconfiguration Review",
    "800OFF": "Offlined for 800 MHz Band Reconfiguration Review",
    "929COM": "929.0125-929.4875 /MHz review completed",
    "929OFF": "929.0125-929.4875 MHz w/i 120 km of US/CA border",
    "AATCGE": "Generate Grant for Assignment/Transfer",
    "AATCPD": "Populate Partition/Disaggregation Tables",
    "ACSCOM": "Associated Call Sign Review Completed",
    "ACSOFF": "Offlined for Associated Call Sign Review",
    "ADDCOM": "Manual Address Correction Complete",
    "ADDOFF": "Offlined for Manual Address Correction",
    "AFCOM": "AFTRCC Review Completed",
    "AFOFF": "Offlined for AFTRCC Review",
    "AFRCOM": "Application for Review Consideration Completed",
    "AFROFF": "Offlined for Application for Review Consideration",
    "ALCOM": "Alert List Review Completed",
    "ALOFF": "Offlined for Alert List Review",
    "AMSCOM": "AM Station Review Completed",
    "AMSTA": "Offlined for AM Station Review",
    "AOCCOM": "CA county coordination review completed",
    "AOCOFF": "County completely in CA coordination zone, D/23=N",
    "AOCOM": "Alien Ownership Review Completed",
    "AONCOM": "Area of Operation = N or U review completed",
    "AONOFF": "Area of Operation = N or U and D/23=Y",
    "AOOFF": "Offlined for Alien Ownership Review",
    "AOPCOM": "Coordinate review (N/Line A, E/Line C) completed",
    "AOPOFF": "Coordinates N/Line A, E/Line C, D/23=N",
    "APACC": "Application Accepted",
    "APCON": "Application Consented",
    "APCONS": "Application Consummated",
    "APCRTC": "Litigation or Court Action Closed",
    "APCRTO": "Litigation or Court Action Open",
    "APDIS": "Application Dismissed",
    "APDIS1": "Application Dismissed due to Aged Return",
    "APDIS2": "Application Dismissed due to Parent Facility Expir",
    "APDIS3": "Application Dismissed due to Parent Facility Assig",
    "APGRP": "Application Granted in Part",
    "APGRT": "Application Granted",
    "APKILL": "Application Killed",
    "APOCOM": "Coser Spec Cond Review (155.475 MHz) completed",
    "APOOFF": "Coser Spec Cond Review (155.475 MHz)",
    "APPASS": "Application Assigned by Manager",
    "APPCNV": "Application Converted",
    "APPCOM": "Change of applicant type code review completed",
    "APPINA": "Saved Application Inactivated Due to Grant",
    "APPINB": "Saved Application Inactivated Due to Dismissal",
    "APPINC": "Saved Application Inactivated Due to Kill",
    "APPIND": "Saved Application Inactivated Due to Consent",
    "APPOFF": "Offlined change of applicant type code review",
    "APRTN": "Application Returned",
    "APRVC": "Review Application for Canceled Cosers",
    "APRVCC": "Canceled Coser Application Review Completed",
    "APRVI": "Review Application for Canceled Iracs",
    "APRVIC": "Canceled Iracs Application Review Completed",
    "APTER": "Application Terminated",
    "APTR2": "Application Set to Returned Status",
    "APWD": "Application Withdrawn",
    "ARECOM": "Area of Operation Review Completed",
    "AREOFF": "Offlined for Area of Operation Review",
    "ASCCOM": "Associated Call Sign Review Completed",
    "ASCOFF": "Offlined for Associated Call Sign Review",
    "ATCOM": "Attachment Review Completed",
    "ATOFF": "Offlined for Attachment Review",
    "ATTCOM": "Attachment Received",
    "ATTOFF": "Offlined for Attachment",
    "AUDCAN": "Audit Response - License Canceled",
    "AUDEX": "License excluded from audit",
    "AUDMOD": "Audit Response - License Modified",
    "AUDOPR": "Audit Response - License Operational",
    "AUDUNX": "License audit exclusion reversed",
    "AUTHGC": "Generate Consent Authorization",
    "AUTHGE": "Generate Authorization",
    "AUTHPC": "Consent Authorization Printed",
    "AUTHPR": "Authorization Printed",
    "AUTHRG": "Generate Reference Copy Authorization",
    "AUTHRL": "Generate Registration Letter",
    "AUTHRP": "Reference Copy Authorization Printed",
    "AUTRLP": "Registration Letter Printed",
    "BIDCOM": "Bidding Credit data Review Completed",
    "BIDOFF": "Offlined for Bidding Credit data Review",
    "BILCOM": "Offline for Billing Completed",
    "BILOFF": "Offlined for Billing",
    "BKPCOM": "Bankruptcy Review Completed",
    "BKPOFF": "Offlined for Bankruptcy Review",
    "BLDCOM": "Buildout Notification Review Completed",
    "BLDOFF": "Offlined for Buildout Notification Review",
    "BNDCOM": "Bandwidth Review Completed",
    "BNDOFF": "Bandwidth Review (Coser/Irac Major/Minor Failed)",
    "BOCOM": "NT/EX Buildout Untimely Filing Review Complete",
    "BOOFF": "Offlined for NT/EX Buildout Untimely Filing Review",
    "BORDCM": "Border Coordinate Review Completed",
    "BORDOF": "Offlined for Border Coordinate Review",
    "BQCOM": "Basic Qualification Review Completed",
    "BQOFF": "Offlined for Basic Qualification Review",
    "BRECOM": "BR/ED Review Completed",
    "BREOFF": "Offlined for BR/ED",
    "CAECOM": "Review of Coser Errors Completed",
    "CAEOFF": "Review Coser Errors",
    "CANCGE": "Generate Cancel Coser",
    "CANCOM": "Manual Coser Review Completed",
    "CANCSE": "Cancel Coser Sent to Canada",
    "CANDOF": "Offlined for Developmental Coser Review",
    "CANFRC": "Forced Coser Review Completed",
    "CANFRV": "Review - Forced Coser Canceled Due to Major Mod",
    "CANGE": "Generate New Coser",
    "CANMOF": "Offlined for Manual Coser Review",
    "CANNSE": "Notification Coser Sent to Canada",
    "CANOGE": "Generate On-Air Coser",
    "CANOSE": "On-Air Coser Sent to Canada",
    "CANPS": "New Coser Sent to Canada (PG Paired Frequency)",
    "CANRE": "Received from Canada",
    "CANRGE": "Generate Recon Coser",
    "CANRSE": "Recon Coser Sent to Canada",
    "CANSC": "Coser Screening Completed",
    "CANSE": "New Coser Sent to Canada",
    "CECOM": "CE Review Completed",
    "CEOFF": "Offlined for CE Review",
    "CFBCOM": "C/F Block Review Completed",
    "CFBOFF": "Offlined for C/F Block Review",
    "CG2COM":  "CGSA review completed",
    "CG2OFF":  "Offlined CGSA is larger than SAB",
    "CGSCOM": "Alt CGSA study completed",
    "CGSOFF": "Offlined to review alt CGSA study",
    "CIBCOM": "CIB Action Completed",
    "CIBOFF": "Offlined for CIB Action",
    "CIPE1": "Resumption Of Payments (Elect To Resume Payments)",
    "CIPE2": "Amnesty - Bid",
    "CIPE3": "Amnesty - Prepayment Credit",
    "CIPE4": "Disaggregation - Prepayment",
    "CIPE5": "Disaggregation - Resume Payment",
    "CIPE6": "Prepayment - 30 MHz",
    "CIPE7": "Cannot Afford Prepayment (Surrender Markets)",
    "CLICCM": "Canceled license review completed",
    "CLICOF": "Review pending App for removal of canceled license",
    "CLSCOM": "Closed Bidding data Review Completed",
    "CLSOFF": "Offlined for Review of Closed Bidding data",
    "CMTCOM": "T1/T2/T3 Commercial License Review Complete",
    "CMTOFF": "Offlined for T1/T2/T3 Commercial License Review",
    "COMCOM": "Compliance with Section 27.1203 Review Completed",
    "COMOFF": "Offlined for Compliance w/ Section 27.1203 Review",
    "CONASD": "Consent set aside; Application returned to pending",
    "CONCOM": "Consummation Review Completed",
    "CONEX": "Construction Date Extended",
    "CONRE": "Call Sign Assignment Consummated - Please Review",
    "CONREV": "Consummation Reversed",
    "CONSEX": "Consummation Date Extended",
    "CONSF": "Application Failed to Consummate Before Deadline",
    "CONSGE": "Generate consummation",
    "CONSN": "Applicant Notification of Failure to Consummate",
    "CONSRV": "Review Consummation - Notification Review",
    "CONSY": "Consummation Notification Received",
    "COR": "Internal Correction Applied",
    "CORADD": "Internal Correction - License Added",
    "COVEX": "Coverage Date Extended",
    "COVNT": "Required Notification of Const/Coverage",
    "CPCOM": "Review for CPOFF Completed",
    "CPLCOM": "CP Location Review Completed",
    "CPLOFF": "CP Location North of Line A or East of Line C.",
    "CPOCOM": "Review for CP OFF Air Completed",
    "CPOFF": "Offlined for CPOFF Review",
    "CPOOFF": "Offlined for CP Off Air Review",
    "CSACOM": "Four-Letter Call Sign Assignment Complete",
    "CSAOFF": "Offline for Four-Letter Call Sign Assignment",
    "CSPCOM": "Coser Spec Cond Review (155.475 MHz) Completed",
    "CSPOFF": "Offlined for Coser Spec Cond Review (155.475 MHz)",
    "CSROFF": "Offlined because Amateur Call Sign Range Exhausted",
    "CTACOM": "Cable TV/Attributable Interest Review Completed",
    "CTAOFF": "Offlined for Cable TV/Attributable Interest Review",
    "CZCCOM": "Coordination Zone Check Completed",
    "CZCOFF": "Offlined for Coordination Zone Check",
    "CZRCOM": "Canadian Zone Review Complete",
    "CZROFF": "Offlined for Canadian Zone Review",
    "DATCOR": "Data Correction Applied",
    "DBCOM": "DO/DM Consolidation Review Complete",
    "DBOFF": "Offlined for DO/DM Consolidation Review",
    "DCIACO": "DCIA FRN Review Completed",
    "DCIAOF": "Offlined for DCIA FRN Review",
    "DEMCCZ": "Demonstration-Coser clearance zone chk not created",
    "DEMCGE": "Demonstration - Coser clearance not created",
    "DEMCMO": "Demonstration - Coser manual offline not created",
    "DEMCOM": "Demonstration Review Completed",
    "DEMOFF": "Offlined for Demonstration Review",
    "DEVCOM": "Developmental Review Completed",
    "DEVOFF": "Offlined for Developmental Review",
    "DIREV": "Dismissed Application Reversed",
    "DISORD": "Dismissed by Order",
    "DMCCOM": "Demonstration - Coser clearance closed",
    "DMMCOM": "Demonstration - Coser manual offline closed",
    "DMZCOM": "Demonstration - Coser clearance zone check closed",
    "DSHCOM": "Manual Domestic MMSI Number Assignment Complete",
    "DSHOFF": "Offline for Dom. MMSI Assignment-Range Exhausted",
    "DTBCOM": "Date of Birth Review Completed",
    "DTBOFF": "Offlined for Date of Birth Review",
    "DTSCOM": "Cable TV/Attributable Interest Review Completed",
    "DTSOFF": "Offlined for P & D of DV/TZ Services Review",
    "DUMOFF": "Dummy offline to prevent IAP grant",
    "DWVCOM": "Waiver/Deferral of Fees Review Completed",
    "DWVOFF": "Offlined for Waiver/Deferral of Fees",
    "EFCAPR": "Application receipt email failed: CORES email",
    "EFCFRN": "FRN Association email failed: CORES email",
    "EFRCOM": "Electronic Filing Review Completed",
    "EFROFF": "Offline for Mandatory Electronic Filing Review",
    "EFUAPR": "Application receipt email failed: ULS email",
    "EFUFRN": "FRN Association email failed: ULS email",
    "EFURNW": "Public Safety Renewal email failed: ULS email",
    "ELGCOM": "Eligibility Review Completed",
    "ELGOFF": "Offlined For Eligibility Review",
    "ENFCOM": "Enforcement Bureau Action Completed",
    "ENFOFF": "Offlined for Enforcement Bureau Action",
    "ENGCOM": "Engineering Review Completed",
    "ENGOFF": "Offlined for Engineering Review",
    "ESCAPR": "Application receipt email sent: CORES email",
    "ESCFRN": "FRN Association email sent: CORES email",
    "ESUAPR": "Application receipt email sent: ULS email",
    "ESUFRN": "FRN Association email sent: ULS email",
    "ESURNW": "Public Safety Renewal email sent: ULS email",
    "EXCOM": "Extension of Time Review Completed",
    "EXOFF": "Offlined for Extension of Time Review",
    "EXPCOM": "Manual License Status Change Completed",
    "EXPOFF": "Offlined for Manual License Status Change",
    "FAACOM": "UNICOM mutual exclusivity check completed",
    "FAAOFF": "Offlined for UNICOM mutual exclusivity check",
    "FCRCOM": "Frequency Coordination Review Completed",
    "FCROFF": "Offlined for Frequency Coordination Review",
    "FORCOM": "Forbearance/Already Occurred Review Completed",
    "FOROFF": "Offlined for Forbearance/Already Occurred Review",
    "FRCCOM": "FRC_OP_Class Code/Endorsement review complete",
    "FRCOFF": "Offlined for FRC_OP_Class Code/Endorsement review",
    "FRDCOM": "Forbearance Date Review Completed",
    "FRDOFF": "Offline for Forbearance Date Review",
    "FTCONN": "Future Consent Did Not Occur",
    "FTGRTN": "Future Grant Did Not Occur",
    "FTRCON": "Future Consent",
    "FTRGRT": "Future Grant",
    "FVCOM": "Fee Validation Completed",
    "FVDCOM": "Fee Determination Completed",
    "FVDOFF": "Offlined for Fee Determination",
    "FVOFF": "Offlined for Fee Validation",
    "FVPCNF": "Payment Confirmed",
    "FVPCOM": "Payment Verification Completed",
    "FVPOFF": "Offlined for Payment Verification",
    "FXCOM": "Faxed Attachment Review Completed",
    "FXOFF": "Offlined for Faxed Attachment",
    "GAPBEG": "GAP Period Begins",
    "GAPPRO": "Offlined for GAP Processing",
    "GEOCOM": "Geographic Overlap Review Completed",
    "GEOOFF": "Offlined for Geographic Overlap Review",
    "GFRCOM": "Grandfathered Station Review Completed",
    "GFROFF": "Offlined for Grandfathered Station Review",
    "GMRCOM": "GMRS Application Review Completed",
    "GMROFF": "Offlined for GMRS Application Review",
    "GRCOM": "Grant Fail Review Completed",
    "GROFF": "Review Application.  Grant Failed.",
    "GRREV": "Granted Application Reversed",
    "GRTORD": "Granted by Order",
    "GSOCOM": "GSO Review Completed",
    "GSOOFF": "Offlined for GSO Review",
    "HFRCOM": "HF Enroute/App 27 Review Completed",
    "HFROFF": "Offlined for HF Enroute/App 27 Review",
    "HRGCOM": "Hearing Review Completed",
    "HRGOFF": "Offlined for Hearing",
    "IFRBGE": "Generate IFRB Notification",
    "IFRBRE": "Received from IFRB",
    "IFRBSE": "IFRB Sent",
    "INACOM": "Inactive Call Sign Review Complete",
    "INAOFF": "Offlined for Inactive Call Sign Review",
    "INSCOM": "Installment Payment data Review Completed",
    "INSOFF": "Offlined for Review of Installment Payment data",
    "INTDUP": "Internal Duplicate Requested",
    "INVCOM": "Involuntary/Involuntary Date Review Completed",
    "INVOFF": "Offlined for Involuntary/Involuntary Date Review",
    "IQCHK": "Offlined for IQ Registered Location Coord Review",
    "IQCOM": "IQ Registered Location Coord Review Completed",
    "IRACC2": "Condition 2 Received from IRAC",
    "IRACC3": "Condition 3 Received from IRAC",
    "IRACCA": "Generate Cancel IRAC",
    "IRACCS": "Cancel IRAC Sent",
    "IRACER": "IRAC application contains errors",
    "IRACFG": "Generate FAA/IRAC",
    "IRACFS": "FAA/IRAC Sent",
    "IRACGE": "Generate IRAC",
    "IRACIN": "Sent to IRAC (Informational)",
    "IRACRE": "Received from IRAC",
    "IRACRO": "Clearance returned from Irac with objection",
    "IRACRV": "Offlined for Irac STA/Demonstration Review",
    "IRACSC": "IRAC Screening Completed",
    "IRACSE": "IRAC--Sent to OET",
    "IRAFRC": "Forced Irac Review Completed",
    "IRAFRV": "Review - Forced Irac Canceled Due to Major Mod",
    "ISHCOM": "Manual Intl MMSI Number Assignment Complete",
    "ISHOFF": "Offline for Intl MMSI Assignment-Range Exhausted",
    "LBOCOM": "NT/EX Lower Buildout Untimely Filing Review Comple",
    "LBOOFF": "Offlined for NT/EX Lower Buildout Untimely Filing",
    "LDACOM": "Licensing Division Analysis Completed",
    "LDAOFF": "Offlined for Licensing Division Analysis",
    "LEGCOM": "Legal Review Completed",
    "LEGOFF": "Offlined for Legal Review",
    "LETACG": "Generate Audit Cancellation Letter",
    "LETACS": "Audit Cancellation Letter Sent",
    "LETAFU": "License Audit Follow up Letter Sent",
    "LETARG": "Generate Application Receipt Letter",
    "LETATG": "Generate Audit Termination Letter",
    "LETATS": "Audit Termination Letter Sent",
    "LETAUS": "License Audit Letter Sent",
    "LETCAG": "Generate Cancellation Letter",
    "LETCAS": "Cancellation Letter Sent",
    "LETCMG": "Generate Consummation Reminder Letter",
    "LETCMS": "Consummation Reminder Letter Sent",
    "LETCNG": "Generate Construction/Coverage Reminder Letter",
    "LETCNS": "Construction/Coverage Reminder Letter Sent",
    "LETCOG": "Generate Coser HIA Return Letter",
    "LETCOS": "Coser HIA Return Letter Sent",
    "LETDCS": "Failure to Notify Dismissal Letter Sent",
    "LETDFG": "Generate Deleted Frequency Letter",
    "LETDFS": "Deleted Frequency Letter Sent",
    "LETDIG": "Generate Dismissal Letter",
    "LETDIH": "Hold Dismissal Letter Text",
    "LETDIS": "Dismissal Letter Sent",
    "LETDLG": "Generate Unprocessable Dismissal Letter Live Money",
    "LETDLS": "Unprocessable Dismissal Letter Sent for Live Money",
    "LETDUG": "Generate Unprocessable Dismissal Letter",
    "LETDUS": "Unprocessable Dismissal Letter Sent",
    "LETFAG": "Generate FRN Association/Change Letter",
    "LETGIH": "Hold Grant in Part Letter Text",
    "LETGIP": "Generate Grant in Part Letter",
    "LETGIS": "Grant in Part Letter Sent",
    "LETLTG": "Generate License Termination Letter",
    "LETLTH": "Hold License Termination Letter Text",
    "LETLTS": "License Termination Letter Sent",
    "LETNNG": "Generate Aircraft Termination Letter",
    "LETNNS": "Aircraft Termination Letter Sent",
    "LETONS": "Ownership Notification Letter Sent",
    "LETPDG": "Generate Pack Dismissal Letter",
    "LETPRG": "Generate Pack Return Letter",
    "LETREG": "Generate Renewal Reminder Letter",
    "LETRES": "Renewal Reminder Letter Sent",
    "LETRTG": "Generate Return Letter",
    "LETRTH": "Hold Return Letter Text",
    "LETRTS": "Return Letter Sent",
    "LETRUG": "Generate Unprocessable Return Letter",
    "LETRUS": "Unprocessable Return Letter Sent",
    "LETSE": "Letter Sent to Applicant",
    "LETSTG": "Generate Ship Termination Letter",
    "LETSTS": "Ship Termination Letter Sent",
    "LEXCOM": "Expired License Review Complete",
    "LEXOFF": "Offlined for Expired License Review",
    "LIASS": "License Assigned (Full Assignment)",
    "LIAUA": "Administrative Update Applied",
    "LICALL": "License Call Sign was Changed",
    "LICAN": "License Canceled",
    "LICARE": "License Cancellation Reversed",
    "LICCNV": "License Converted",
    "LIDUP": "Duplicate Authorization Generated",
    "LIEXP": "License Status Set to Expired",
    "LIISS": "License Issued",
    "LIMOD": "License Modified",
    "LIPASS": "License Assigned (Partial Assignment)",
    "LIPND": "License Assigned (Partition/Disagg)",
    "LIPPND": "License Issued from a Partial/P&D Assignment",
    "LIPUR": "License Purged",
    "LIREIN": "License Reinstated",
    "LIREN": "License Renewed",
    "LIRIN1": "License reinstated-parent station was un-canceled",
    "LIRIN2": "License reinstated-parent station was undismissed",
    "LIRMD": "License Renewed and Modified",
    "LIRTAC": "License Returned to Active Status",
    "LITERE": "License Termination Reversed",
    "LITERM": "License Terminated",
    "LITIN": "License TIN Added",
    "LITRAN": "License Transferred",
    "LMNCOM": "Licensee Name Mismatch Review Complete",
    "LMNOFF": "Offlined for Licensee Name Mismatch",
    "LMSCOM": "LMS Review Completed",
    "LMSOFF": "Offlined for LMS Review",
    "LNMCOM": "Licensee name change review completed",
    "LNMOFF": "Licensee name changed in CDBS",
    "LOCCOM": "Location Review Completed",
    "LOCOFF": "Offlined for Location Review",
    "LSLCOM": "P&D of Leased Services Review Completed",
    "LSLOFF": "Offlined for P&D of Leased Services Review",
    "LTFAPR": "Application Receipt Letter failed delivery",
    "LTFFRN": "FRN Association Letter failed delivery",
    "LTSAPR": "Application Receipt Letter sent",
    "LTSFRN": "FRN Association Letter sent",
    "MADOFF": "Offlined for Insufficient Name/Mailing Address",
    "MARCOM": "RO/RM Market application review complete",
    "MAROFF": "Offlined for RO/RM Market application review",
    "MCCOM": "MC - FC Cancellation Review Completed",
    "MCOFF": "Offlined for MC - FC Cancellation Review",
    "MDRCOM": "Mail Delivery Review Completed",
    "MDROFF": "Offlined for Mail Delivery Review",
    "MEXCOM": "Mexico Coordination Review Completed",
    "MEXGE": "Generate Notification for Mexico",
    "MEXING": "Generate Notification for Mexico (Informational)",
    "MEXINS": "Notification Sent to Mexico (Informational)",
    "MEXOFF": "Offlined for Mexico Coordination",
    "MEXRE": "Received from Mexico",
    "MEXSC": "Mexico Screening Completed",
    "MEXSE": "Notification Sent to Mexico",
    "MJCOM": "Major Amendment Review Completed",
    "MJREV": "Offlined for Major Amendment Review",
    "MMBCOM": "MMB Referral Completed",
    "MMBOFF": "Offlined for MMB Referral",
    "MMCOM": "Multiple Mod (Conflict) Review Completed",
    "MMMCOM": "Major Merger Review Completed",
    "MMMOFF": "Offlined for Major Merger Review",
    "MMOFF": "Offlined for Multiple Mod (Conflict) Review",
    "MMWCOM": "Merger Review Completed",
    "MMWOFF": "Offlined for Merger Review",
    "MOBCOM": "Mobile Count Review Completed",
    "MOBOFF": "Offlined for Mobile Count",
    "MRSCOM": "NT/EX Multiple Private/Commercial Review Complete",
    "MRSOFF": "Offlined for NT/EX Multiple Priv/Comm Review",
    "MTSCOM": "MTS Completed",
    "MTSOFF": "Offlined for MTS",
    "MULCOM": "MULTICOM Review Completed",
    "MULOFF": "Offlined for MULTICOM Review",
    "MXCOM": "MX Processing Completed",
    "MXNCOM": "Mutually Exclusive Review (no rules) Completed",
    "MXNOFF": "Offlined for Mutually Exclusive Review (no rules)",
    "MXOFF": "Offlined for MX Processing",
    "MXRCOM": "Mutually Exclusive Review (rules) Completed",
    "MXROFF": "Offlined for Mutually Exclusive Review (rules)",
    "MZRCOM": "Mexican Zone Review Complete",
    "MZROFF": "Offlined for Mexican Zone Review",
    "NEPCOM": "NEPA Review Completed",
    "NEPOFF": "Offlined for NEPA Review",
    "NNCOM": "N-Number Conflict with Amateur Call Sign Review Co",
    "NNOFF": "Offlined for N-Number Conflict with Amateur Call S",
    "NPCOM": "Northern Pacific Review Completed",
    "NPOFF": "Offlined for Northern Pacific Review",
    "NTACOM": "NT/EX Amendment Review Completed",
    "NTAOFF": "Offlined for NT/EX Amendment Review",
    "NTECOM": "NT/EX Error Review Complete",
    "NTEOFF": "Offlined for NT/EX Error Review",
    "NTGCOM": "NT Grant Hold Review Complete",
    "NTGOFF": "Offlined for NT Grant Hold",
    "NTICOM": "NTIA Coordination Review Completed",
    "NTIOFF": "Offlined for NTIA Coordination Review",
    "NWACOM": "Non-Wireless Activity Review Completed",
    "NWAOFF": "Offlined for Non-Wireless Activity Review",
    "OPPRE": "Opposition Received",
    "ORISS": "Order Issued",
    "PARREB": "Parent Station, Once Silent, Is Broadcasting Again",
    "PARSIL": "Parent Station Went Silent",
    "Page": "69pa_codes26",
    "PARTAA": "Partial AA For Site-based License Consummated",
    "PCCOM": "Private/Commercial Review Completed",
    "PCECOM": "Review of Pre-Canada Errors Completed",
    "PCEOFF": "Review Pre-Canada Errors",
    "PCKCOM": "Pack Review Completed",
    "PCKOFF": "Offlined for Pack Review",
    "PCOFF": "Offlined for Private/Commercial Review",
    "PCRCOM": "Public Coast Review Completed",
    "PCROFF": "Offlined for Public Coast Review",
    "PFCOM": "Public Fixed Review Completed",
    "PFDCOM": "Review of PFD at Border Completed",
    "PFDOFF": "Offline for PFD at Border Review",
    "PFOFF": "Offlined for Public Fixed Review",
    "PFRCL": "Petition for Reconsideration Period Closed",
    "PFRCOM": "Petition for Reconsideration Review Completed",
    "PFRDN": "Petition for Reconsideration Denied",
    "PFRGR": "Petition for Reconsideration Granted",
    "PFROFF": "Offlined for Petition for Reconsideration Review",
    "PFROP": "Petition for Reconsideration Period Open",
    "PFRRE": "Petition for Reconsideration Received",
    "PH1COM": "Review of Phase 1 application completed",
    "PH1OFF": "Offlined for Review of Phase 1 application",
    "PH2COM": "Review of Phase 2 application completed",
    "PH2OFF": "Offlined for Review of Phase 2 application",
    "PLWD": "Pleading Withdrawn",
    "PMTCOM": "Installment Payment Review Completed",
    "PMTOFF": "Offlined for Installment Payment Review",
    "PNACC": "Accepted for Filing PN Generated",
    "PNACGE": "Generate Action PN",
    "PNACT": "Action PN Generated",
    "PNAF0": "Generate Informational Accepted for Filing PN",
    "PNAFG2": "Generate 14 Day Accepted for Filing PN",
    "PNAFGE": "Generate Accepted for Filing PN",
    "PNLIAA": "Generate Action PN for Parent Facility Assignment",
    "PNLICA": "Generate Action PN for Parent Facility Cancellation",
    "PNLIEX": "Generate Action PN for Parent Facility Expiration",
    "PNLIMD": "Generate Action PN for Parent Facility Mod",
    "PNLIRE": "Generate Action PN for Parent Facility Renewal",
    "PRCOM": "Puerto Rico Review Completed",
    "PRCOM2": "Puerto Rico Review Completed",
    "PROFF": "Offlined for Notification from Puerto Rico",
    "PROFF2": "Waiting for Notification from Puerto Rico",
    "PTDCOM": "Petition to Deny Review Completed",
    "PTDOFF": "Offlined for Petition to Deny Review",
    "PWVCOM": "Grand/waiver/func integ question review completed",
    "PWVOFF": "Checked Y to grand/waiver/func integ question 8c",
    "QZCOM": "NRAO/NRRO Review Completed",
    "QZCOM2": "NRAO/NRRO Review Completed",
    "QZOFF": "Offlined for Notification from NRAO/NRRO",
    "QZOFF2": "Waiting for Notification from NRAO/NRRO",
    "RCDUP": "Reference Copy Duplicate Requested",
    "RCSCOM": "Receiver Call Sign Review Completed",
    "RCSOFF": "Offlined for Receiver Call Sign Review",
    "RDLCOM": "Redlight Review Completed",
    "RDLOFF": "Offlined for Red Light",
    "RECAA": "Assignment of Authorization Received",
    "RECAM": "Amendment Received",
    "RECAP": "Additional Pleading Received",
    "RECAU": "Administrative Update Received",
    "RECCA": "Cancellation of License Received",
    "RECCB": "C Block Election Received",
    "RECCHK": "Offlined For Coser Recon Check",
    "RECCOM": "Coser Recon Check Completed",
    "RECDC": "Data Correction Application Applied",
    "RECDU": "Duplicate License Request Received",
    "RECEX": "Request for Extension of Time Received",
    "RECLL": "Spectrum Leasing Application Received",
    "RECMD": "Modification Received",
    "RECMJ": "Major Modification Received",
    "RECMN": "Minor Modification Received",
    "RECNE": "New Application Received",
    "RECNT": "Required Notification Received",
    "RECNTC": "Notification of Construction/Coverage Received",
    "RECPTD": "Petition to Deny Received",
    "RECRL": "Registration of Location/Link Received",
    "RECRM": "Renewal/Modification Received",
    "RECRO": "Renewal Only Received",
    "RECTC": "Transfer of Control Received",
    "RECUP": "Unprocessable Filing Received",
    "RECWD": "Withdrawal of Application Received",
    "REFER": "Application Referred",
    "REGCOM": "Regulatory Status Review Complete",
    "REGOFF": "Offlined for Regulatory Status Review",
    "RLMCOM": "Rulemaking Decision Completed",
    "RLMOFF": "Offlined for Rulemaking",
    "RLPR": "Registration Letter Printed",
    "RMCOM": "Renewal/Mod Review Completed",
    "RMOFF": "Offlined for Renewal/Mod Review",
    "ROBCOM": "Renewal: Buildout Deadline Review Completed",
    "ROBOFF": "Renewal: Offlined for Buildout Deadline Review",
    "ROMCOM": "Untimely filed RO/RM Review Completed",
    "ROMOFF": "Offlined for Untimely filed RO/RM Review",
    "RONCOM": "RO: Pending NT Review completed",
    "RONOFF": "RO: Offlined for Pending NT Review",
    "ROXCOM": "RO: Pending EX Review completed",
    "ROXOFF": "RO: Offlined for Pending EX Review",
    "RPLRE": "Reply Received",
    "RSCCOM": "Radio Service Review Completed",
    "RSCOFF": "Offlined for Radio Service Review",
    "RSPCOM": "Reduced Service Providers Review Completed",
    "RSPOFF": "Offlined for Reduced Service Providers Review",
    "RTPEND": "Returned to Pending",
    "SABCOM": "Radial data height-power limit review completed",
    "SABOFF": "Offlined",
    "SBGCOM": "Radial data height-power limit review completed",
    "SBGOFF": "Offlined",
    "SCCOM": "Southern California Review Completed",
    "SCHCOM": "Four-Letter Call Sign Review Complete",
    "SCHOFF": "Offline for Four-Letter Call Sign Review",
    "SCOFF": "Offlined for Southern California Review",
    "SCRCOM": "Manual Domestic MMSI Number Assignment Complete",
    "SCROFF": "Offlined because Ship Call Range Exhausted",
    "SCSCOM": "Subscriber Call Sign Review Completed",
    "SCSOFF": "Offlined for Subscriber Call Sign Review",
    "SDACOM": "Additional SID review completed",
    "SDAOFF": "Offlined for review of SID",
    "SDNCOM": "New SID review completed",
    "SDNOFF": "Offlined-review request to add new SIDs",
    "SETFTR": "Set Future Grant",
    "SGACOM": "Review of Slow Growth - Application - Completed",
    "SGAOFF": "Offlined to Review Slow Growth - Application",
    "SGLCOM": "Review of Slow Growth - License - Completed",
    "SGLOFF": "Offlined to Review Slow Growth - License",
    "SHXCOM": "Ship Exemption Review Complete",
    "SHXOFF": "Offlined for Ship Exemption Review",
    "SLPBEG": "Streamline Processing Period Begins",
    "SLPEX": "Streamline Processing Period Ended - Grant Pending",
    "SLPEXC": "Streamline Processing Exclusivity Review Completed",
    "SLPEXR": "Offlined for Streamline Processing Exclusivity",
    "SLPREM": "Removed from Streamline Processing",
    "SMBCOM": "SMR Buildout Review Completed",
    "SMBOFF": "Offlined for SMR Buildout Review",
    "SMICOM": "Review of SMR Special Conditions Completed",
    "SMIOFF": "Offlined for Review of SMR Special Conditions",
    "STACCZ": "STA - Coser clearance zone check was not created",
    "STACGE": "STA - Coser clearance was not created",
    "STACMO": "STA - Coser manual offline was not created",
    "STACOM": "STA Review Completed",
    "STAOFF": "Offlined for STA Review",
    "STBCOM": "Bill for Emergency STA Completed",
    "STBOFF": "Offlined to Bill for Emergency STA",
    "STCCOM": "STA - Coser clearance closed",
    "STMCOM": "STA - Coser manual offline closed",
    "STZCOM": "STA - Coser clearance zone check closed",
    "SYSGRT": "New Systematic Call Sign Assigned",
    "TACOM": "TowAir Check Completed",
    "TAOFF": "Offlined for TowAir",
    "TCCOM": "Tower Tolerance check Completed",
    "TCOFF": "Offlined for Tower Tolerance Check",
    "TINCOM": "TIN/Name Verification Completed",
    "TINOFF": "Offlined for TIN/Name Verification",
    "TLBCOM": "Tribal Land Bidding Credit Review Completed",
    "TLBOFF": "Offlined for Tribal Land Bidding Credit Review",
    "TLCOFF": "Offlined for 180 Day Review of Tribal Land Certs",
    "TLOOFF": "Offlined for Other Tribal Land Selected",
    "TOWCOM": "Review of 47 C.F.R. 17.14 Showing completed",
    "TOWGCM": "Failed Grant-Time Tower Clearance Check Completed",
    "TOWGE": "Generate Tower",
    "TOWGRT": "Failed Grant-Time Tower Clearance Check",
    "TOWOFF": "Offlined for review of 47 C.F.R. 17.14 Showing",
    "TOWRE": "Received from Tower",
    "TOWSE": "Sent to Tower",
    "TULSAP": "Application Converted to TULS",
    "TULSCN": "License Converted to TULS",
    "UCFCOM": "Untimely Constructed/Filed Review Completed",
    "UCFOFF": "Offlined for Untimely Constructed/Filed Review",
    "UCOCOM": "Untimely Construction Review Completed",
    "UCOOFF": "Offlined for Untimely Construction Review",
    "UMRCOM": "Utility Mobile Review Completed",
    "UMROFF": "Offlined for Utility Mobile Review",
    "UNCOM": "UNICOM Review Completed",
    "UNOFF": "Offlined for UNICOM Review",
    "UPDIS": "Unprocessable Filing Disposed",
    "VANCOM":  "Schedule D Eligibility A or C review completed",
    "VANGRT": "Vanity Call Sign Assigned",
    "VANOFF":  "Schedule D Eligibility A or C",
    "WACOM": "Other Wireless Activity Review Completed",
    "WAOFF": "Offlined for Other Wireless Activity Review",
    "WAVCOM": "Wavier Review Completed",
    "WAVOFF": "Offlined for Waiver Review",
    "WDREV": "Withdrawn Application Reversed",
    "WNTCOM": "NT Waiver Removal Review Complete",
    "WNTOFF": "Offlined for NT Waiver Removal Review",
    "WRECOM": "Waiver Renewal- 30 days Review Completed",
    "WREOFF": "Offlined for Renewal Waiver- 30 days Review",
    "WSCCOM": "Wavier Special Condition Review Completed",
    "WSCOFF": "Offlined for Waiver Special Condition Review",
    "XBRCOM": "Transborder Coordination Completed",
    "XBROFF": "Offlined for Transborder Coordination",
    "YRCNT": "Yearly Required Notification of Construction"
};
